// ---------------------------------------------------------------------------
// Ingredient Highlighter — highlight food words in instruction text
//
// Uses a standalone comprehensive food dictionary to highlight any food term
// that appears in recipe instruction text. This is intentionally decoupled
// from both the recipe's own ingredient list and the ingredient categorizer
// so it catches partial matches — e.g. "onion" in the instructions highlights
// even when the ingredient list says "red onion" — and covers terms that
// the categorizer's narrower keyword map doesn't include.
//
// The dictionary is organized by category for maintainability. The regex
// sorts terms longest-first so multi-word phrases match before their
// component words (e.g. "olive oil" before "oil", "cream cheese" before
// "cream").
// ---------------------------------------------------------------------------

import type { ReactNode } from "react";

function escapeRegex(str: string): string {
  return str.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
}

// ---------------------------------------------------------------------------
// FOOD_DICTIONARY
//
// Comprehensive list of food/ingredient words that appear in recipe
// instruction text. Organized by category for readability and maintenance.
//
// Rules:
//   - Singular forms only; the regex appends optional plural suffix (e?s)
//   - Multi-word terms included as-is (longest-first matching handles priority)
//   - Regional and international spelling variants included
//   - Cuts and preparations for meats included
//   - No cooking verbs, equipment, measurements, or process descriptors
// ---------------------------------------------------------------------------

const FOOD_DICTIONARY: string[] = [
  // -------------------------------------------------------------------------
  // PRODUCE — Vegetables
  // -------------------------------------------------------------------------
  "artichoke",
  "arugula",
  "asparagus",
  "aubergine",
  "avocado",
  "bean sprout",
  "beet",
  "beetroot",
  "bell pepper",
  "bitter melon",
  "bok choy",
  "broccoli",
  "broccolini",
  "brussels sprout",
  "burdock",
  "butternut squash",
  "cabbage",
  "capsicum",
  "carrot",
  "cassava",
  "cauliflower",
  "celeriac",
  "celery",
  "celery root",
  "chard",
  "chicory",
  "chinese cabbage",
  "collard green",
  "corn",
  "courgette",
  "cucumber",
  "daikon",
  "delicata squash",
  "edamame",
  "eggplant",
  "endive",
  "fennel",
  "fennel bulb",
  "fiddlehead",
  "garlic",
  "garlic clove",
  "cloves of garlic",
  "clove of garlic",
  "green bean",
  "green cabbage",
  "green onion",
  "heart of palm",
  "horseradish",
  "iceberg lettuce",
  "jalapeño",
  "jicama",
  "kale",
  "kohlrabi",
  "leek",
  "lemon",
  "lettuce",
  "lime",
  "lotus root",
  "microgreen",
  "mizuna",
  "mushroom",
  "napa cabbage",
  "nopales",
  "okra",
  "onion",
  "orange",
  "pak choi",
  "parsnip",
  "pattypan squash",
  "pea",
  "pepperoncini",
  "poblano",
  "potato",
  "pumpkin",
  "purple cabbage",
  "radicchio",
  "radish",
  "red cabbage",
  "red onion",
  "red pepper",
  "rocket",
  "romaine",
  "rutabaga",
  "savoy cabbage",
  "scallion",
  "serrano",
  "shallot",
  "snap pea",
  "snow pea",
  "spaghetti squash",
  "spinach",
  "spring onion",
  "squash",
  "sugar snap pea",
  "swede",
  "sweet corn",
  "sweet onion",
  "sweet pepper",
  "sweet potato",
  "swiss chard",
  "taro",
  "tomato",
  "turnip",
  "watercress",
  "white onion",
  "yellow onion",
  "yellow pepper",
  "yellow squash",
  "yuca",
  "zucchini",

  // -------------------------------------------------------------------------
  // PRODUCE — Fresh Mushroom Varieties
  // -------------------------------------------------------------------------
  "button mushroom",
  "chanterelle",
  "cremini",
  "enoki",
  "king oyster mushroom",
  "maitake",
  "oyster mushroom",
  "porcini",
  "portobello",
  "shiitake",
  "trumpet mushroom",

  // -------------------------------------------------------------------------
  // FRUITS
  // -------------------------------------------------------------------------
  "apple",
  "apricot",
  "banana",
  "blackberry",
  "blood orange",
  "blueberry",
  "boysenberry",
  "cantaloupe",
  "cherry",
  "clementine",
  "coconut",
  "cranberry",
  "date",
  "dragon fruit",
  "durian",
  "elderberry",
  "fig",
  "gooseberry",
  "grape",
  "grapefruit",
  "guava",
  "honeydew",
  "jackfruit",
  "kiwi",
  "kumquat",
  "lychee",
  "mandarin",
  "mango",
  "melon",
  "mulberry",
  "nectarine",
  "papaya",
  "passion fruit",
  "passionfruit",
  "peach",
  "pear",
  "persimmon",
  "pineapple",
  "plantain",
  "plum",
  "pomegranate",
  "pomelo",
  "quince",
  "raspberry",
  "rhubarb",
  "star fruit",
  "strawberry",
  "tamarind",
  "tangerine",
  "watermelon",

  // -------------------------------------------------------------------------
  // FRUITS — Dried
  // -------------------------------------------------------------------------
  "currant",
  "dried apricot",
  "dried cherry",
  "dried cranberry",
  "dried fig",
  "dried mango",
  "prune",
  "raisin",
  "sultana",
  "sun-dried tomato",
  "sundried tomato",

  // -------------------------------------------------------------------------
  // FRESH HERBS
  // -------------------------------------------------------------------------
  "basil",
  "bay leaf",
  "bay leaves",
  "chervil",
  "chive",
  "cilantro",
  "coriander leaf",
  "dill",
  "epazote",
  "flat-leaf parsley",
  "fresh basil",
  "fresh chive",
  "fresh cilantro",
  "fresh dill",
  "fresh ginger",
  "fresh mint",
  "fresh parsley",
  "fresh rosemary",
  "fresh sage",
  "fresh tarragon",
  "fresh thyme",
  "ginger root",
  "kaffir lime leaf",
  "lavender",
  "lemon balm",
  "lemon thyme",
  "lemon verbena",
  "lemongrass",
  "lovage",
  "marjoram",
  "mint",
  "oregano",
  "parsley",
  "pandan leaf",
  "rosemary",
  "sage",
  "savory",
  "sorrel",
  "spearmint",
  "tarragon",
  "thyme",
  "thai basil",
  "vietnamese coriander",

  // -------------------------------------------------------------------------
  // MEAT & POULTRY — Whole Cuts and Preparations
  // -------------------------------------------------------------------------
  "bacon",
  "beef",
  "beef brisket",
  "beef cheek",
  "beef chuck",
  "beef loin",
  "beef ribs",
  "beef shank",
  "beef short rib",
  "beef tenderloin",
  "bison",
  "bologna",
  "bone-in chicken",
  "bratwurst",
  "bresaola",
  "chicken",
  "chicken breast",
  "chicken drumstick",
  "chicken leg",
  "chicken thigh",
  "chicken wing",
  "chorizo",
  "coppa",
  "corned beef",
  "duck",
  "duck breast",
  "duck confit",
  "duck leg",
  "flank steak",
  "ground beef",
  "ground chicken",
  "ground lamb",
  "ground meat",
  "ground pork",
  "ground turkey",
  "ground veal",
  "guanciale",
  "ham",
  "ham hock",
  "kielbasa",
  "lamb",
  "lamb chop",
  "lamb leg",
  "lamb loin",
  "lamb rack",
  "lamb shank",
  "lardons",
  "mince",
  "mortadella",
  "pancetta",
  "pork",
  "pork belly",
  "pork chop",
  "pork loin",
  "pork ribs",
  "pork shoulder",
  "pork tenderloin",
  "prosciutto",
  "pulled pork",
  "quail",
  "rabbit",
  "ribeye",
  "salami",
  "sausage",
  "short rib",
  "skirt steak",
  "speck",
  "steak",
  "strip steak",
  "t-bone",
  "turkey",
  "turkey breast",
  "turkey leg",
  "veal",
  "veal chop",
  "venison",
  "wagyu",

  // -------------------------------------------------------------------------
  // SEAFOOD & FISH
  // -------------------------------------------------------------------------
  "anchovy",
  "arctic char",
  "barramundi",
  "black bass",
  "bluefish",
  "bonito",
  "bream",
  "branzino",
  "catfish",
  "caviar",
  "clam",
  "cockle",
  "cod",
  "crab",
  "crawfish",
  "crayfish",
  "dungeness crab",
  "eel",
  "fish",
  "flounder",
  "grouper",
  "haddock",
  "halibut",
  "herring",
  "king crab",
  "langoustine",
  "lobster",
  "mackerel",
  "mahi-mahi",
  "monkfish",
  "mussel",
  "octopus",
  "oyster",
  "perch",
  "pike",
  "pollock",
  "prawns",
  "red snapper",
  "rockfish",
  "roe",
  "salmon",
  "sardine",
  "scallop",
  "sea bass",
  "sea bream",
  "sea urchin",
  "shrimp",
  "skate",
  "smoked salmon",
  "snapper",
  "sole",
  "squid",
  "swordfish",
  "tilapia",
  "trout",
  "tuna",
  "turbot",
  "uni",
  "whitefish",

  // -------------------------------------------------------------------------
  // DAIRY & EGGS
  // -------------------------------------------------------------------------
  "blue cheese",
  "brie",
  "burrata",
  "butter",
  "buttermilk",
  "camembert",
  "cheddar",
  "colby",
  "condensed milk",
  "cotija",
  "cottage cheese",
  "cream",
  "cream cheese",
  "crème fraîche",
  "creme fraiche",
  "double cream",
  "egg",
  "egg white",
  "egg yolk",
  "emmental",
  "evaporated milk",
  "farmer cheese",
  "feta",
  "fontina",
  "gorgonzola",
  "gouda",
  "gruyère",
  "gruyere",
  "half and half",
  "halloumi",
  "havarti",
  "heavy cream",
  "jack cheese",
  "jarlsberg",
  "kashkaval",
  "kefir",
  "labneh",
  "manchego",
  "mascarpone",
  "milk",
  "monterey jack",
  "mozzarella",
  "muenster",
  "oat milk",
  "paneer",
  "parmesan",
  "parmigiano-reggiano",
  "pecorino",
  "pepper jack",
  "plant milk",
  "provolone",
  "queso blanco",
  "queso fresco",
  "queso",
  "ricotta",
  "romano",
  "roquefort",
  "single cream",
  "skim milk",
  "sour cream",
  "stilton",
  "swiss cheese",
  "whipping cream",
  "whole milk",
  "yogurt",
  "yoghurt",

  // -------------------------------------------------------------------------
  // GRAINS, PASTA & BREAD
  // -------------------------------------------------------------------------
  "angel hair",
  "arborio",
  "arborio rice",
  "bagel",
  "basmati",
  "basmati rice",
  "baguette",
  "barley",
  "biscuit",
  "black rice",
  "bread",
  "breadcrumb",
  "brioche",
  "brown rice",
  "buckwheat",
  "bulgur",
  "bun",
  "ciabatta",
  "couscous",
  "cracker",
  "croissant",
  "crouton",
  "egg noodle",
  "english muffin",
  "farfalle",
  "farro",
  "fettuccine",
  "focaccia",
  "fusilli",
  "glass noodle",
  "gnocchi",
  "jasmine rice",
  "jasmine",
  "lasagna",
  "lasagne",
  "lavash",
  "linguine",
  "lo mein noodle",
  "long-grain rice",
  "macaroni",
  "medium-grain rice",
  "millet",
  "naan",
  "noodle",
  "oat",
  "oatmeal",
  "orzo",
  "pappardelle",
  "panko",
  "pasta",
  "penne",
  "pita",
  "pizza dough",
  "polenta",
  "popcorn",
  "quinoa",
  "ravioli",
  "red rice",
  "rice",
  "rice noodle",
  "rice paper",
  "rigatoni",
  "risotto rice",
  "roll",
  "roti",
  "rye",
  "rye bread",
  "semolina",
  "short-grain rice",
  "sourdough",
  "spaghetti",
  "spelt",
  "sticky rice",
  "sushi rice",
  "tagliatelle",
  "tortellini",
  "tortilla",
  "tortilla chip",
  "triticale",
  "udon noodle",
  "vermicelli",
  "white bread",
  "white rice",
  "whole grain bread",
  "whole wheat bread",
  "wild rice",
  "wonton wrapper",
  "wonton",

  // -------------------------------------------------------------------------
  // DRY GOODS & BAKING
  // -------------------------------------------------------------------------
  "agave",
  "agave nectar",
  "almond flour",
  "all-purpose flour",
  "arrowroot",
  "baking powder",
  "baking soda",
  "bicarbonate of soda",
  "bread flour",
  "brown sugar",
  "cake flour",
  "caster sugar",
  "chocolate",
  "chocolate chip",
  "cocoa",
  "cocoa powder",
  "coconut flour",
  "coconut sugar",
  "confectioners sugar",
  "corn flour",
  "cornstarch",
  "cornmeal",
  "cream of tartar",
  "dark chocolate",
  "demerara sugar",
  "dry active yeast",
  "flour",
  "food coloring",
  "gelatin",
  "glucose syrup",
  "golden syrup",
  "granulated sugar",
  "honey",
  "icing sugar",
  "instant yeast",
  "maple syrup",
  "milk chocolate",
  "molasses",
  "oat flour",
  "palm sugar",
  "panela",
  "pastry flour",
  "pectin",
  "potato starch",
  "powdered sugar",
  "raw sugar",
  "rice flour",
  "self-raising flour",
  "semolina flour",
  "shortening",
  "simple syrup",
  "spelt flour",
  "sugar",
  "tapioca",
  "tapioca starch",
  "treacle",
  "turbinado sugar",
  "unsweetened chocolate",
  "vanilla extract",
  "vanilla",
  "vanilla bean",
  "vanilla paste",
  "white chocolate",
  "whole wheat flour",
  "yeast",

  // -------------------------------------------------------------------------
  // SPICES & DRIED SEASONINGS
  // -------------------------------------------------------------------------
  "achiote",
  "aleppo pepper",
  "allspice",
  "ancho chile",
  "ancho chili",
  "ancho chilli",
  "anise",
  "annatto",
  "berbere",
  "black cardamom",
  "black pepper",
  "black sesame",
  "caraway",
  "cardamom",
  "cayenne",
  "celery salt",
  "celery seed",
  "chile flake",
  "chile powder",
  "chili flake",
  "chili powder",
  "chilli flake",
  "chilli powder",
  "chinese five spice",
  "chipotle",
  "cinnamon",
  "clove",
  "coriander",
  "coriander seed",
  "crushed red pepper",
  "cumin",
  "curry leaf",
  "curry powder",
  "dill seed",
  "dried basil",
  "dried chile",
  "dried chili",
  "dried chilli",
  "dried cilantro",
  "dried dill",
  "dried ginger",
  "dried lavender",
  "dried mint",
  "dried oregano",
  "dried parsley",
  "dried rosemary",
  "dried sage",
  "dried thyme",
  "dukkah",
  "fennel seed",
  "fenugreek",
  "five spice",
  "garam masala",
  "garlic powder",
  "garlic salt",
  "ginger powder",
  "ground clove",
  "ground coriander",
  "ground cumin",
  "ground ginger",
  "ground nutmeg",
  "harissa",
  "herbes de provence",
  "italian seasoning",
  "juniper berry",
  "kaffir lime",
  "kosher salt",
  "lemon pepper",
  "mace",
  "mustard powder",
  "mustard seed",
  "nigella seed",
  "nutmeg",
  "old bay",
  "onion powder",
  "paprika",
  "pepper",
  "pickling spice",
  "pink peppercorn",
  "ras el hanout",
  "red pepper flake",
  "saffron",
  "salt",
  "sea salt",
  "smoked paprika",
  "smoked salt",
  "star anise",
  "sumac",
  "szechuan pepper",
  "szechuan peppercorn",
  "table salt",
  "tamarind powder",
  "turmeric",
  "urfa pepper",
  "vanilla powder",
  "white pepper",
  "za'atar",
  "zaatar",

  // -------------------------------------------------------------------------
  // OILS, VINEGARS & CONDIMENTS
  // -------------------------------------------------------------------------
  "apple cider vinegar",
  "avocado oil",
  "balsamic glaze",
  "balsamic vinegar",
  "barbecue sauce",
  "bbq sauce",
  "black vinegar",
  "canola oil",
  "chile garlic sauce",
  "chile oil",
  "chile sauce",
  "chili garlic sauce",
  "chili oil",
  "chili sauce",
  "chilli garlic sauce",
  "chilli oil",
  "chilli sauce",
  "chipotle sauce",
  "coconut aminos",
  "coconut oil",
  "cooking spray",
  "cooking wine",
  "dijon mustard",
  "dressing",
  "duck fat",
  "fish sauce",
  "flaxseed oil",
  "ghee",
  "gochujang",
  "grape seed oil",
  "grapeseed oil",
  "hollandaise",
  "hoisin",
  "hoisin sauce",
  "hot sauce",
  "ketchup",
  "ketjap manis",
  "lard",
  "lemon juice",
  "lime juice",
  "maggi",
  "mango chutney",
  "marsala",
  "mayo",
  "mayonnaise",
  "mirin",
  "mustard",
  "nonstick spray",
  "oil",
  "olive oil",
  "orange juice",
  "oyster sauce",
  "palm oil",
  "peanut oil",
  "pesto",
  "ponzu",
  "red wine vinegar",
  "rice wine vinegar",
  "rice vinegar",
  "safflower oil",
  "sambal",
  "sambal oelek",
  "sesame oil",
  "sherry",
  "sherry vinegar",
  "shoyu",
  "soy sauce",
  "sriracha",
  "suet",
  "sunflower oil",
  "sweet chile sauce",
  "sweet chili sauce",
  "sweet chilli sauce",
  "tahini",
  "tamari",
  "teriyaki",
  "teriyaki sauce",
  "tomato sauce",
  "tallow",
  "truffle oil",
  "vegetable oil",
  "vinaigrette",
  "vinegar",
  "walnut oil",
  "white wine vinegar",
  "white vinegar",
  "worcestershire",
  "worcestershire sauce",

  // -------------------------------------------------------------------------
  // WINES & SPIRITS (used in cooking)
  // -------------------------------------------------------------------------
  "beer",
  "bourbon",
  "brandy",
  "champagne",
  "cognac",
  "gin",
  "kahlua",
  "kirsch",
  "marsala wine",
  "mezcal",
  "port",
  "prosecco",
  "red wine",
  "rice wine",
  "rum",
  "sake",
  "shaoxing",
  "shaoxing wine",
  "sherry wine",
  "tequila",
  "vodka",
  "white wine",
  "wine",

  // -------------------------------------------------------------------------
  // CANNED & JARRED GOODS
  // -------------------------------------------------------------------------
  "beef broth",
  "beef stock",
  "bone broth",
  "bouillon",
  "broth",
  "canned bean",
  "canned chickpea",
  "canned corn",
  "canned lentil",
  "canned salmon",
  "canned tuna",
  "capers",
  "chicken broth",
  "chicken stock",
  "chutney",
  "coconut cream",
  "coconut milk",
  "crushed tomato",
  "diced tomato",
  "fish broth",
  "fish stock",
  "jam",
  "jelly",
  "kimchi",
  "marmalade",
  "minced garlic",
  "minced ginger",
  "miso paste",
  "olives",
  "paste",
  "peeled tomato",
  "pickles",
  "preserved lemon",
  "preserves",
  "roasted red pepper",
  "salsa",
  "sauerkraut",
  "stock",
  "tomato paste",
  "tomato puree",
  "tomato purée",
  "vegetable broth",
  "vegetable stock",
  "whole tomato",

  // -------------------------------------------------------------------------
  // NUTS & SEEDS
  // -------------------------------------------------------------------------
  "almond",
  "almond butter",
  "brazil nut",
  "candied nut",
  "candied pecan",
  "cashew",
  "cashew butter",
  "chestnut",
  "chia seed",
  "coconut flake",
  "flax seed",
  "flaxseed",
  "hazelnut",
  "hemp heart",
  "hemp seed",
  "macadamia",
  "mixed nut",
  "peanut",
  "peanut butter",
  "pecan",
  "pine nut",
  "pistachio",
  "poppy seed",
  "pumpkin seed",
  "sesame seed",
  "sunflower seed",
  "toasted almond",
  "toasted pecan",
  "walnut",

  // -------------------------------------------------------------------------
  // LEGUMES & BEANS
  // -------------------------------------------------------------------------
  "adzuki bean",
  "bean",
  "black bean",
  "black-eyed pea",
  "borlotti bean",
  "broad bean",
  "butter bean",
  "cannellini bean",
  "chickpea",
  "fava bean",
  "flageolet",
  "garbanzo",
  "great northern bean",
  "green lentil",
  "kidney bean",
  "lentil",
  "lima bean",
  "mung bean",
  "navy bean",
  "pinto bean",
  "red lentil",
  "soybeans",
  "split pea",
  "urad dal",
  "white bean",
  "yellow lentil",

  // -------------------------------------------------------------------------
  // ASIAN & INTERNATIONAL INGREDIENTS
  // -------------------------------------------------------------------------
  "adobo sauce",
  "agar agar",
  "ajvar",
  "annatto paste",
  "bean curd",
  "bean paste",
  "black bean paste",
  "black bean sauce",
  "bonito flake",
  "chile bean paste",
  "chile paste",
  "chili bean paste",
  "chili paste",
  "chilli bean paste",
  "chilli paste",
  "chipotle in adobo",
  "daikon radish",
  "dashi",
  "dashi stock",
  "doenjang",
  "doubanjiang",
  "dried mushroom",
  "dried seaweed",
  "dried shrimp",
  "fish cake",
  "fish paste",
  "furikake",
  "galangal",
  "gochugaru",
  "koji",
  "kombu",
  "makrut lime",
  "makrut lime leaf",
  "miso",
  "nori",
  "pandan",
  "pappadam",
  "preserved black bean",
  "shrimp paste",
  "soba noodle",
  "tamarind paste",
  "tempe",
  "tempeh",
  "tofu",
  "wakame",
  "wasabi",

  // -------------------------------------------------------------------------
  // GENERIC FOOD TERMS (sauce names, components, garnishes)
  // -------------------------------------------------------------------------
  "batter",
  "bisque",
  "compote",
  "coulis",
  "crust",
  "custard",
  "dipping sauce",
  "drizzle",
  "dough",
  "filling",
  "foam",
  "fondue",
  "frosting",
  "fruit",
  "ganache",
  "garnish",
  "glaze",
  "gravy",
  "green",
  "icing",
  "marinade",
  "meringue",
  "mousse",
  "pickle",
  "protein",
  "purée",
  "puree",
  "ragù",
  "ragu",
  "reduction",
  "relish",
  "rub",
  "salad",
  "sauce",
  "spread",
  "stuffing",
  "syrup",
  "topping",
  "vegetable",
  "whipped cream",
  "zest",
];

// ---------------------------------------------------------------------------
// Module-level derived values
// ---------------------------------------------------------------------------

/**
 * Deduplicated food words sorted longest-first so multi-word phrases
 * match before their component words (e.g. "olive oil" before "oil").
 */
const FOOD_WORDS: string[] = [...new Set(FOOD_DICTIONARY)].sort(
  (a, b) => b.length - a.length,
);

/** Pre-built regex matching any food word with optional plural suffix. */
const FOOD_REGEX = new RegExp(
  `\\b(${FOOD_WORDS.map(escapeRegex).join("|")})(?:e?s)?\\b`,
  "gi",
);

// ---------------------------------------------------------------------------
// highlightIngredients
// ---------------------------------------------------------------------------

/**
 * Highlight food/ingredient words within instruction step text.
 *
 * Returns React nodes with matched words wrapped in styled spans.
 * Uses word-boundary matching to avoid false highlights (e.g. "oil" won't
 * match inside "foil"). Multi-word phrases are matched before single words
 * due to longest-first sort order.
 *
 * @param text - Raw instruction step text
 * @returns Array of strings and React span elements, or the original string
 *          if no food words were found.
 */
export function highlightIngredients(text: string): ReactNode {
  if (!text) return text;

  // Reset lastIndex — the regex is module-level and stateful
  FOOD_REGEX.lastIndex = 0;

  const parts: ReactNode[] = [];
  let lastIndex = 0;
  let match: RegExpExecArray | null;
  let key = 0;

  while ((match = FOOD_REGEX.exec(text)) !== null) {
    if (match.index > lastIndex) {
      parts.push(text.slice(lastIndex, match.index));
    }
    parts.push(
      <span key={key++} className="font-semibold text-primary">
        {match[0]}
      </span>,
    );
    lastIndex = FOOD_REGEX.lastIndex;
  }

  if (parts.length === 0) return text;

  if (lastIndex < text.length) {
    parts.push(text.slice(lastIndex));
  }

  return parts;
}
